package POJOs;
// Generated 13-oct-2023 14:06:49 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Asientos generated by hbm2java
 */
public class Asientos  implements java.io.Serializable {


     private Integer idAsiento;
     private Salas salas;
     private Integer numeroAsiento;
     private String estadoHaciento;
     private Set<Boletos> boletoses = new HashSet<Boletos>(0);

    public Asientos() {
    }

    public Asientos(Salas salas, Integer numeroAsiento, String estadoHaciento, Set<Boletos> boletoses) {
       this.salas = salas;
       this.numeroAsiento = numeroAsiento;
       this.estadoHaciento = estadoHaciento;
       this.boletoses = boletoses;
    }
   
    public Integer getIdAsiento() {
        return this.idAsiento;
    }
    
    public void setIdAsiento(Integer idAsiento) {
        this.idAsiento = idAsiento;
    }
    public Salas getSalas() {
        return this.salas;
    }
    
    public void setSalas(Salas salas) {
        this.salas = salas;
    }
    public Integer getNumeroAsiento() {
        return this.numeroAsiento;
    }
    
    public void setNumeroAsiento(Integer numeroAsiento) {
        this.numeroAsiento = numeroAsiento;
    }
    public String getEstadoHaciento() {
        return this.estadoHaciento;
    }
    
    public void setEstadoHaciento(String estadoHaciento) {
        this.estadoHaciento = estadoHaciento;
    }
    public Set<Boletos> getBoletoses() {
        return this.boletoses;
    }
    
    public void setBoletoses(Set<Boletos> boletoses) {
        this.boletoses = boletoses;
    }
}


