package POJOs;
// Generated 13-oct-2023 14:06:49 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Boletos generated by hbm2java
 */
public class Boletos  implements java.io.Serializable {


     private Integer idBoleto;
     private Asientos asientos;
     private Funciones funciones;
     private Usuarios usuarios;
     private String nombreCliente;
     private BigDecimal precio;
     private Date fechaCompra;
     private String metodoPago;

    public Boletos() {
    }

    public Boletos(Asientos asientos, Funciones funciones, Usuarios usuarios, String nombreCliente, BigDecimal precio, Date fechaCompra, String metodoPago) {
       this.asientos = asientos;
       this.funciones = funciones;
       this.usuarios = usuarios;
       this.nombreCliente = nombreCliente;
       this.precio = precio;
       this.fechaCompra = fechaCompra;
       this.metodoPago = metodoPago;
    }
   
    public Integer getIdBoleto() {
        return this.idBoleto;
    }
    
    public void setIdBoleto(Integer idBoleto) {
        this.idBoleto = idBoleto;
    }
    public Asientos getAsientos() {
        return this.asientos;
    }
    
    public void setAsientos(Asientos asientos) {
        this.asientos = asientos;
    }
    public Funciones getFunciones() {
        return this.funciones;
    }
    
    public void setFunciones(Funciones funciones) {
        this.funciones = funciones;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getNombreCliente() {
        return this.nombreCliente;
    }
    
    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }
    public String getMetodoPago() {
        return this.metodoPago;
    }
    
    public void setMetodoPago(String metodoPago) {
        this.metodoPago = metodoPago;
    }
}


