package POJOs;
// Generated 13-oct-2023 14:06:49 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Funciones generated by hbm2java
 */
public class Funciones  implements java.io.Serializable {


     private Integer idFuncion;
     private Peliculas peliculas;
     private Salas salas;
     private Date fechaHora;
     private Set<Boletos> boletoses = new HashSet<Boletos>(0);

    public Funciones() {
    }

    public Funciones(Peliculas peliculas, Salas salas, Date fechaHora, Set<Boletos> boletoses) {
       this.peliculas = peliculas;
       this.salas = salas;
       this.fechaHora = fechaHora;
       this.boletoses = boletoses;
    }
   
    public Integer getIdFuncion() {
        return this.idFuncion;
    }
    
    public void setIdFuncion(Integer idFuncion) {
        this.idFuncion = idFuncion;
    }
    public Peliculas getPeliculas() {
        return this.peliculas;
    }
    
    public void setPeliculas(Peliculas peliculas) {
        this.peliculas = peliculas;
    }
    public Salas getSalas() {
        return this.salas;
    }
    
    public void setSalas(Salas salas) {
        this.salas = salas;
    }
    public Date getFechaHora() {
        return this.fechaHora;
    }
    
    public void setFechaHora(Date fechaHora) {
        this.fechaHora = fechaHora;
    }
    public Set<Boletos> getBoletoses() {
        return this.boletoses;
    }
    
    public void setBoletoses(Set<Boletos> boletoses) {
        this.boletoses = boletoses;
    }
}


