package POJOs;
// Generated 13-oct-2023 14:06:49 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Salas generated by hbm2java
 */
public class Salas  implements java.io.Serializable {


     private Integer idSala;
     private Integer numeroSala;
     private Integer capacidad;
     private Set<Funciones> funcioneses = new HashSet<Funciones>(0);
     private Set<Asientos> asientoses = new HashSet<Asientos>(0);

    public Salas() {
    }

    public Salas(Integer numeroSala, Integer capacidad, Set<Funciones> funcioneses, Set<Asientos> asientoses) {
       this.numeroSala = numeroSala;
       this.capacidad = capacidad;
       this.funcioneses = funcioneses;
       this.asientoses = asientoses;
    }
   
    public Integer getIdSala() {
        return this.idSala;
    }
    
    public void setIdSala(Integer idSala) {
        this.idSala = idSala;
    }
    public Integer getNumeroSala() {
        return this.numeroSala;
    }
    
    public void setNumeroSala(Integer numeroSala) {
        this.numeroSala = numeroSala;
    }
    public Integer getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(Integer capacidad) {
        this.capacidad = capacidad;
    }
    public Set<Funciones> getFuncioneses() {
        return this.funcioneses;
    }
    
    public void setFuncioneses(Set<Funciones> funcioneses) {
        this.funcioneses = funcioneses;
    }
    public Set<Asientos> getAsientoses() {
        return this.asientoses;
    }
    
    public void setAsientoses(Set<Asientos> asientoses) {
        this.asientoses = asientoses;
    }
}


