package POJOs;
// Generated 13-oct-2023 14:06:49 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer idUsuario;
     private String nombreUsuario;
     private String email;
     private short contrasenia;
     private String rol;
     private Set<Boletos> boletoses = new HashSet<Boletos>(0);

    public Usuarios() {
    }

	
    public Usuarios(short contrasenia) {
        this.contrasenia = contrasenia;
    }
    public Usuarios(String nombreUsuario, String email, short contrasenia, String rol, Set<Boletos> boletoses) {
       this.nombreUsuario = nombreUsuario;
       this.email = email;
       this.contrasenia = contrasenia;
       this.rol = rol;
       this.boletoses = boletoses;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public short getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(short contrasenia) {
        this.contrasenia = contrasenia;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public Set<Boletos> getBoletoses() {
        return this.boletoses;
    }
    
    public void setBoletoses(Set<Boletos> boletoses) {
        this.boletoses = boletoses;
    }
}


